*  Advent of Code mode for Emacs

A lightweight Emacs minor mode to help manage Advent of Code (AoC) puzzle solutions.

* Overview

- Advent-mode is a minor mode that shows AoC context (year, day) and cookie status in the
  mode line.

- Directory layout: =path/to/aoc/year<YYYY>/day<DD>=

- Features

  - Global minor mode autodetecting solution directories

  - Display year/day/cookie in the mode line

  - Manage the AoC session cookie

  - Optionally persist the cookie in =.authinfo=

  - Create a new AoC day (with boilerplate files)

  - Browse existing day solutions

  - Open the current problem using eww

  - Fetch and open the puzzle input

  - Submit an answer to AoC

* Installation / Configuration

This package requires Emacs 29.1+ to run. I use it on Emacs 30.1 so here's my
configuration using =package-vc=:

#+begin_src emacs-lisp
(use-package advent-mode
  :vc (:url "https://github.com/vkazanov/advent-mode")
  :custom
  ;; REQUIRED: where your AoC solutions live
  (advent-root-dir "~/projects/aoc")
  ;; OPTIONAL: Copy these into each new day directory (absolute or
  ;; relative to advent-root-dir)
  (advent-new-files '("solution.py" "aoc.py"))
  :config
  ;; Enable advent-mode when possible in files under advent-root-dir.
  ;; Otherwise, advent-mode can be enabled locally using
  ;; .dir-locals.el.
  (global-advent-mode 1))
#+end_src

* Quick Start

- Enable =global-advent-mode=, set =advent-root-dir= and then:

  - =M-x advent-login= to store your AoC session cookie when prompted

    - To retrieve the cookie, login into adventofcode.com in your browser, inspect
      cookies, copy the value of the "session" cookie

    - it is possible to use auth source (the =.authinfo= file) to store the cookie, see
      =advent-session-provider= for comments

  - =M-x advent-open-day= to open an existing AoC day directory

  - =M-x advent-create-day= to create a new AoC day directory

  - =M-x advent-browse-problem-page= to view the current problem page in EWW

  - =M-x advent-fetch-input= to fetch/open the input for the current day

  - =M-x advent-submit-answer= to submit an answer (prompts for answer and level)

Notes:

- The first time you fetch an input, Advent Mode will download it using your AoC session
  cookie.

- If the cookie is missing or expired, you'll be prompted to log in.
